apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-p4ul
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-p4ul
    app.kubernetes.io/part-of: tkrw-pr712-0075-0053-app
  name: devfile-sample-p4ul
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-p4ul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-p4ul
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-p4ul@sha256:13b1190bacd02a1ab65d91d4a7c09627ca1dd274a94d7b8415d75cfa59533742
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
