apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-p4ul
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-p4ul@sha256:13b1190bacd02a1ab65d91d4a7c09627ca1dd274a94d7b8415d75cfa59533742
        name: my-nodejs
        resources: {}
status: {}
